Feature/linevych tokners
20210502-FE/linevych_tokners pull request #1
Opened 2021-07-18 15:42 UTC by Roman240594

2021-09-15 20:08 UTC, JuliaSavych requested changes

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +        <div class="header__bg"></div>
краще винести в banner

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                    <a class="logo__link" href="index.html">
href="/"

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                <picture class="logo">
a > picture

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                        <div class="header__button">
.auth-btns

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +        <section class="p-home__banner">
а де батьківський .p-home?

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                    <div class="sup-title p-home__banner-sup-title">
sub-title not suP

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                            <div class="p-home__info-img-wrapper p-home__info-img_green">
p-home__info-img_green це модифікатор класу p-home__info-img
модифікатор без елемента чи блоку не існує

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                                For <span class="p-home__info-title_blue">Holders</span>
модифікатор без елемента чи блоку не існує

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +        <section class="p-home__banner">
![Screenshot from 2021-09-03 17-20-44](https://user-images.githubusercontent.com/19241160/132020745-a337290c-a1d0-4635-bb8c-312b0717f06b.png)
відступ зліва замалий (1500px)

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                        <nav class="nav">
.nav.header__nav

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                    <div class="header__nav flex" id="navList">
чому .header__nav відповідає і за кнопки логін і створити акаунт?

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                <div class="p-home__info-inner">
забагато вкладеності, цей клас можна додати до .wrapper
.wrapper.p-home__info-wrapper

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                    <div class="p-home__info-wrapper">
колонка

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +        <section class="p-home__benefit">
benefits

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                <div class="text p-home__benefit-text">
тут можна розділити на p

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +            <div class="p-home p-home__description_bg">
p-home__description_bg модифікатор не існує без класу елемента

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                    <div class="p-home__description-content">
.p-home__description-content це колонки

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                                <p class="p-home__description-item">Team set-up
для чого тут p?

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +        <section class="p-home__weentar">
`flex-direction: row-reverse;`
для чого?

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                <div class="p-home__weentar-text-main">
![Screenshot from 2021-09-15 22-10-53](https://user-images.githubusercontent.com/19241160/133494905-175a6b82-f9c8-4ccf-a5cb-8332c0565391.png)
для чогооооо?
тут щось взагалі не зрозуміле з версткою

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                <details>
![Screenshot from 2021-09-15 22-12-02](https://user-images.githubusercontent.com/19241160/133495034-843d71c9-3ce6-49a0-9cb0-2c3adae35788.png)
![Screenshot from 2021-09-15 22-11-55](https://user-images.githubusercontent.com/19241160/133495035-8e08ae29-88c9-4754-8e37-7ca1240be843.png)
нижній відступ скаче при відкритті

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +        <section class="p-home__detail">
p-home__phases

2021-09-15 20:08 UTC, jules-js commented on app/scss/pages/home/_p-home.scss
> +                    padding: 10 10px;
???

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                    <div class="p-home__detail-column p-home__detail-column_closed">
p-home__detail-column_closed яка роль цього модифікатора?

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                    <div class="p-home__detail-column p-home__detail-column_padding">
p-home__detail-column_padding 
неінформативна назва модифікатора

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                        <div class="p-home__detail-content  p-home__detail-content_two">
зроби це незалежним блоком і на ховер ефект обертання картки з риба-тестом
https://codepen.io/juliasavych/pen/omyzmr

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                    <div class="p-home__detail-dot"></div>
span

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +                <nav class="nav">
.nav.footer__nav

2021-09-15 20:08 UTC, jules-js commented on app/index.html
> +            <div class="footer__nav">
лишній div

2021-09-15 20:08 UTC, jules-js commented on app/js/main.js
> +}
скорочений варіант - https://codepen.io/juliasavych/pen/powdaWN

2021-09-15 20:08 UTC, jules-js commented on app/scss/base/_base.scss
> +        max-width: calc(100% - 10px);
відступ

2021-09-15 20:08 UTC, jules-js commented on app/scss/base/_base.scss
> +        margin: 0 auto;
відступ

2021-09-15 20:08 UTC, jules-js commented on app/scss/base/_base.scss
> +.sup-title {
sub-title

2021-09-15 20:08 UTC, jules-js commented on app/scss/modules/_footer.scss
> +    &__copyright {
copyrights

2021-09-15 20:08 UTC, jules-js commented on app/scss/modules/_header.scss
> +            filter: blur(34px);
https://caniuse.com/?search=filter()

2021-09-15 20:08 UTC, jules-js commented on app/scss/pages/home/_p-home.scss
> +            &_one {
дуплікація стилів

2021-09-15 20:08 UTC, jules-js commented on app/scss/pages/home/_p-home.scss
> +            &_one {
відрізняються тільки background-image

2021-09-15 20:08 UTC, jules-js commented on app/scss/pages/home/_p-home.scss
> +            &_one {
незрозуміло шо за one two three

2021-09-15 20:08 UTC, jules-js commented on app/scss/pages/home/_p-home.scss
> +            margin-bottom: 10px;
а у цього тексту який font-family:, якщо нижче переоприділяєш?

2021-09-15 20:08 UTC, jules-js commented on app/scss/utility/_variables.scss
> +$font-italic: 'CenturyGothic-BoldItalic';
$font-bold-italic:

2021-09-15 20:08 UTC, jules-js commented on app/team.html
> +        <section class="p-team__slider">
p-team де блок?

2021-09-15 20:08 UTC, jules-js commented on app/team.html
> +                        <div class="p-team__slider-arrow"><i class="fas fa-arrow-left"></i></div>
button

2021-09-15 20:08 UTC, jules-js commented on app/team.html
> +                    <div class="p-team__slider-col-wrapper">
колонка

2021-09-15 20:08 UTC, jules-js commented on app/team.html
> +                        <div class="p-team__slider-col">
figure.user-card

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
для чого?

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                    <button class="menu" id="menuBtn">
burger-btn

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +        <section class="p-tokens__banner">
відступній блок p-tokens

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                <div class="p-tokens__banner-inner">
лишня вкладеність
юзай БЕМ міксіни

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                    <div class="p-tokens__banner-discription">
dEscription

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                        <div class="p-tokens__banner-subtitle">Tknrs Token Distribution Schedule Total Supply:</div>
це могли б бути параграфи

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                            <div class="p-tokens__banner-text">Premined Tokens</div>
це могли б бути параграфи

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                            <div class="p-tokens__banner-text">Daily Token Distribution</div>
це могли б бути параграфи

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                    <div class="p-tokens__banner-discription">
тут цифра 100000 вилазить за блок, бо у нього стоїть максимальна ширина
фікс

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                    <div class="p-tokens__prospect-col-wrapper">
колонка

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                        <div class="p-tokens__prospect-col">
незалежний блок

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +                            <div class="p-tokens__prospect-date">
p-tokens__prospect-date і p-tokens__prospect-text я б огорнула у блок і дала відступ зліва

2021-09-15 20:08 UTC, jules-js commented on app/tokens.html
> +
порожні теги в один рядок
`<div class="marking__small marking__small_yellow"></div>`

2021-09-15 20:08 UTC, JuliaSavych commented on app/tokens.html
> +                            <div class="p-tokens__prospect-content flex">
всі нижні елементи в один рядок, не треба збільшувати к-сть рядків шаблону, якщо все вміщається
```
 <div class="p-tokens__prospect-date">Day 90 - Day 365</div>
<div class="p-tokens__prospect-text"> 5M Tokens/Day </div>
```
фікс за бажанням, але скоротиш шаблон так точно

2021-09-15 20:08 UTC, JuliaSavych commented on app/tokens.html
> +                                <div class="marking__small marking__small_blue">
порожні теги в один рядок
<div class="marking__small marking__small_blue"></div>

2021-09-15 20:08 UTC, JuliaSavych commented on app/index.html
> +    <header class="header">
![Screenshot from 2021-09-15 23-01-01](https://user-images.githubusercontent.com/19241160/133501250-6fa7fa8d-1f33-4465-b859-70bb5e680d9c.png)
застилізуй меню нормально

2021-09-15 20:08 UTC, JuliaSavych commented on app/index.html
> +    <header class="header">
кнопки в такому випадку мають бути такі ж як і елементи меню, або чуть відрізнятися

2021-09-15 20:08 UTC, JuliaSavych commented on app/index.html
> +    <header class="header">
в неті багато прикладів стилізації

2021-09-15 20:08 UTC, JuliaSavych commented on app/tokens.html
> +<!DOCTYPE html>
![Screenshot from 2021-09-15 23-03-35](https://user-images.githubusercontent.com/19241160/133501617-fa81e587-a273-4e00-992d-10bce07575a5.png)
як мінімум відступи по боках замалі

2021-09-15 20:08 UTC, JuliaSavych commented on app/team.html
> +<!DOCTYPE html>
![Screenshot from 2021-09-15 23-05-17](https://user-images.githubusercontent.com/19241160/133501827-c67ee239-ff63-442b-afb1-30b1574fc4ec.png)
тут слайдер - картинки не повинні переміщатися вниз
або скрол, або додай слайдер

2021-09-15 20:08 UTC, JuliaSavych commented on app/team.html
> +<!DOCTYPE html>
краще слайдер*

2021-09-15 20:08 UTC, JuliaSavych commented on app/index.html
> +        <section class="p-home__detail">
![Screenshot from 2021-09-15 23-06-32](https://user-images.githubusercontent.com/19241160/133501986-705dc6bf-19bb-4907-8e50-5f451cea8a0d.png)
занадто мала ширина
не ок

2021-09-15 20:08 UTC, JuliaSavych commented on app/index.html
> +        <section class="p-home__description">
![Screenshot from 2021-09-15 23-07-13](https://user-images.githubusercontent.com/19241160/133502122-61a7c6aa-3085-409e-bb06-7836020c762b.png)
тут точно так має бути??

2021-09-15 21:30 UTC, JuliaSavych commented on app/index.html
> +                    <div class="footer__social-circle">
область клікабельності

2021-09-15 21:31 UTC, JuliaSavych commented on app/index.html
> +                        Design by Oleg Kulik
![Screenshot from 2021-09-16 00-30-56](https://user-images.githubusercontent.com/19241160/133512453-f22ad2c7-a106-4f28-b5c5-cb9ce28d70fd.png)
посилання

2021-09-15 21:32 UTC, JuliaSavych commented on app/css/pages/home/p-home.css
> +.p-home__banner {
для чого створювати папку, якщо у ній один файл тільки??

2021-09-17 12:16 UTC, Roman240594 commented on app/index.html
> +                                <p class="p-home__description-item">Team set-up
Щоб розділити текст від нумерації, оскільки цифри одного кольору і шрифру, а літери іншого

2021-09-17 12:28 UTC, Roman240594 commented on app/index.html
> +                <div class="p-home__weentar-text-main">
На мобільній верстці текст над кнопкою затемнений, от я його так і зробив

2021-09-17 12:31 UTC, Roman240594 commented on app/index.html
> +                <details>
Робив по макету. При закритому тексті такі відступи. Хіба буде логічним бронювати місце під текст. А якщо його там буде на 5-10 абзаців більше? Залишати чистий фон, але щоб відступ не скакав?

2021-09-17 12:59 UTC, Roman240594 commented on app/scss/base/_base.scss
> +        max-width: calc(100% - 10px);
В чому проблема з відступом?

2021-09-17 13:49 UTC, Roman240594 commented on app/scss/modules/_header.scss
> +            filter: blur(34px);
https://caniuse.com/?search=filter%3A%20blur

2021-09-17 13:55 UTC, Roman240594 commented on app/scss/pages/home/_p-home.scss
> +            margin-bottom: 10px;
унаслідувався з p-home__phases

2021-09-18 08:31 UTC, merged